# Battery --------------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Debug Logging --------------------
#CONFIG_LOG=y
#CONFIG_LOG_BACKEND_USB_CDC_ACM=y
#CONFIG_LOG_BUFFER_SIZE=16384
#CONFIG_ZMK_LOG_LEVEL_DBG=y
#CONFIG_ZMK_SPLIT_LOG_LEVEL_DBG=y
#CONFIG_RGBLED_WIDGET_LOG_LEVEL_DBG=y