# Prospector -----------------------
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# Encoder --------------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y